name: Purge Pull Requests

on:
  pull_request_target:
    types:
      - opened

permissions:
  issues: write
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          close-pr: true
          lock-pr: true
          pr-lock-reason: "resolved"
          process-only: "prs"
          log-output: false
          pr-comment: This pull request has been automatically closed because this repository does not allow pull requests. If you require to submit a bug report or feature request, please open a new issue with the issue forms.
